framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
